### ISSUE TITLE
unable to find drbbdup library

### ISSUE THREAD

**Issue by sikoushixinyou** [Dynamic-Rabbits/Dynamic-Rabbits#2]
Thanks for taking the time to answer my question. I cannot find the implementation of the drbbdup library that exists in Dynamorio under this link https://github.com/johnfxgalea/dynamorio

**Comment by johnfxgalea** [comment]
Thank you for your interest. You can find drbbdup at this [commit](https://github.com/johnfxgalea/dynamorio/tree/d5ab56405e9a13e0129b873f17b2a186472784de).

If you are specifically interested in drbbdup, note that a lot of the code has been cleaned and merged into DynamoRIO's official repository, which you can find [here](https://github.com/DynamoRIO/dynamorio/tree/master/ext/drbbdup). There is also [documentation](https://dynamorio.org/page_drbbdup.html).
