### ISSUE TITLE
How to find the truncation point

### ISSUE THREAD

**Issue by sikoushixinyou** [Dynamic-Rabbits/Dynamic-Rabbits#5]
Thank you for taking the time to consider my issues. When a basic block needs to be truncated, how to find the truncation point. Where should I find the implementation of this function in the code？

**Comment by johnfxgalea** [comment]
Thank you for your interest.

In the AsiaCCS version, the Utility Rabbit provides this functionality. The following folder contains all the truncators:  https://github.com/Dynamic-Rabbits/Dynamic-Rabbits/tree/experimental-asiaccs2020/utility_bunny/src/app_bb_truncators
