### ISSUE TITLE
How to get the defalult case value?

### ISSUE THREAD

**Issue by sikoushixinyou** [Dynamic-Rabbits/Dynamic-Rabbits#6]
Thank you for taking the time to answer my issues.
in your paper,you give an example bb:
`
mov eax, dword ptr [eax]
mov dword ptr [ebp], eax
mov ecx, dowrd ptr [ebx]
`
why the default(tainted) case value of this example is 0x15(10101)?
I think if the size of this bb's in_out_set is 5,it's default case value is (11111).Is my understanding wrong?

**Comment by johnfxgalea** [comment]
You can find the code responsible for constructing the default case encoding [here](https://github.com/Dynamic-Rabbits/Dynamic-Rabbits/blob/b4374164eea37e8d904f4e4c52bbf0143ab3f4c1/taint_bunny/src/optimisations/fast_path_generator/tb_fp_helper.c#L154). It is pretty simple; it just creates a mask consisting of a series of 1 bits.

Indeed, that's a typo in the paper and should be 0x1F (11111).

Thanks!
